export const TEST = 'TEST';

/* VIEW TYPE CONSTANTS */
/* --- BLOG */
/* --- --- CATEGORIES */
export const SET_BLOG_CATEGORIES_ERROR = 'SET_BLOG_CATEGORIES_ERROR';
export const SET_BLOG_CATEGORIES_ERROR_MESSAGE = 'SET_BLOG_CATEGORIES_ERROR_MESSAGE';
export const SET_BLOG_CATEGORIES_FETCHED = 'SET_BLOG_CATEGORIES_FETCHED';
export const SET_BLOG_CATEGORIES_FETCHING = 'SET_BLOG_CATEGORIES_FETCHING';
export const SET_BLOG_CATEGORIES = 'SET_BLOG_CATEGORIES';
/* --- --- MOST RECENT */
export const SET_BLOG_MOST_RECENT_ERROR = 'SET_BLOG_MOST_RECENT_ERROR';
export const SET_BLOG_MOST_RECENT_ERROR_MESSAGE = 'SET_BLOG_MOST_RECENT_ERROR_MESSAGE';
export const SET_BLOG_MOST_RECENT_FETCHED = 'SET_BLOG_MOST_RECENT_FETCHED';
export const SET_BLOG_MOST_RECENT_FETCHING = 'SET_BLOG_MOST_RECENT_FETCHING';
export const SET_BLOG_MOST_RECENT = 'SET_BLOG_MOST_RECENT';
/* --- --- POSTS */
export const SET_BLOG_POSTS_ERROR = 'SET_BLOG_POSTS_ERROR';
export const SET_BLOG_POSTS_ERROR_MESSAGE = 'SET_BLOG_POSTS_ERROR_MESSAGE';
export const SET_BLOG_POSTS_FETCHED = 'SET_BLOG_POSTS_FETCHED';
export const SET_BLOG_POSTS_FETCHING = 'SET_BLOG_POSTS_FETCHING';
export const SET_BLOG_POSTS = 'SET_BLOG_POSTS';
/* --- --- TAGS */
export const SET_BLOG_TAGS_ERROR = 'SET_BLOG_TAGS_ERROR';
export const SET_BLOG_TAGS_ERROR_MESSAGE = 'SET_BLOG_TAGS_ERROR_MESSAGE';
export const SET_BLOG_TAGS_FETCHED = 'SET_BLOG_TAGS_FETCHED';
export const SET_BLOG_TAGS_FETCHING = 'SET_BLOG_TAGS_FETCHING';
export const SET_BLOG_TAGS = 'SET_BLOG_TAGS';